In [1]:
import pandas as pd
alunos = {'Nome': ["Ricardo", "Pedro", "Roberto", "Carlos"],
         'Nota' : [4, 5.5, 7, 9],
         'Aprovado' : ['Não', 'Sim', 'Não', 'Sim']}

In [2]:
dataframe = pd.DataFrame(alunos)



In [3]:
print(dataframe)

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   5.5      Sim
2  Roberto   7.0      Não
3   Carlos   9.0      Sim


In [8]:
import pandas as pd
objeto1 = pd.Series([2, 6, 9, 10, 5])
print(objeto1)

    0
1   2
2   6
3   9
4  10
5   5


In [12]:
import numpy as np
array = np.array([(2, 6, 9, 10, 5), (6, 12, 2, 9, 10)])
array2 = np.array([2, 6, 9, 10, 5])
print(array)
print(array2)

[[ 2  6  9 10  5]
 [ 6 12  2  9 10]]
[ 2  6  9 10  5]


In [13]:
objeto2 = pd.Series(array2)
print(objeto2)

0     2
1     6
2     9
3    10
4     5
dtype: int32
